#!/bin/bash
JMETER_PATH=/Users/zumo/dev/java-tools/jmeter
USER=es_admin
PASS=password
HOST=192.168.99.100
PORT=9201
INDEX=apachelogs-*
QUERY_CSV=input1K1h.csv
SCROLL_CSV=inputScroll.csv
SHIELD_ENABLED=YES
DOCS_PER_BULK=500
NB_FILES=40